green_route = '臺南公園 ─ 永康 ─ 新化 ─ 玉井';
green_1_route = '新化 ─ 新市 ─ 南科 ─ 善化';
green_2_route = '新化 ─ 新市 ─ 南科 ─ 善化 ─ 山上';
green_3_route = '新化 ─ 新市 ─ 看西 ─ 南科 ─ 善化';
green_4_route = '新化 ─ 新市 ─ 陽光電城 ─ 善化轉運站';
green_5_route = '永康火車站 ─ 潭頂 ─ 大社';
green_6_route = '新化 ─ 潭頂 ─ 大社';
green_7_route = '新化 ─ 大營 ─ 大社';
green_10_route = '新化 ─ 山上';
green_11_route = '新化 ─ 山上 ─ 善化';
green_12_route = '新化 ─ 南化 ─ 玉山';
green_13_route = '新化 ─ 岡林 ─ 左鎮';
green_14_route = '新化 ─ 九層嶺';
green_15_route = '新化 ─ 五甲勢';
green_16_route = '新化 ─ 關廟 ─ 高鐵臺南站';
green_17_route = '安平工業區 ─ 大灣 ─ 新化';
green_20_route = '玉井 ─ 楠西 ─ 永興吊橋';
green_20_1_route = '玉井 ─ 虎頭山';
green_21_route = '玉井 ─ 龜丹油礦';
green_22_route = '玉井 ─ 楠西 ─ 梅嶺';
green_23_route = '玉井 ─ 楠西 ─ 雙溪新社區';
green_24_route = '玉井 ─ 楠西 ─ 曾文水庫管理局';
green_25_route = '玉井 ─ 楠西 ─ 大埔';
green_26_route = '玉井 ─ 甲仙';
green_27_route = '玉井 ─ 南化 ─ 茄苳橋';

blue_route = '安平工業區 ─ 西港 ─ 佳里';
blue_1_route = '佳里 ─ 苓子寮 ─ 西埔內 ─ 南鯤鯓';
blue_2_route = '佳里 ─ 溪底寮 ─ 南鯤鯓';
blue_3_route = '佳里 ─ 蘆竹溝';
blue_10_route = '佳里 ─ 馬沙溝 ─ 將軍漁港';
blue_11_route = '佳里 ─ 城子內 ─ 青鯤鯓';
blue_12_route = '佳里 ─ 後港 ─ 青鯤鯓';
blue_13_route = '佳里 ─ 西寮';
blue_20_route = '佳里 ─ 台區 ─ 青鯤鯓 ─ 將軍漁港';
blue_21_route = '佳里 ─ 義合 ─ 九塊厝';
blue_22_route = '佳里 ─ 七十二份 ─ 九塊厝';
blue_23_route = '安平工業區 ─ 九塊厝';
blue_24_route = '安平工業區 ─ 土城子 ─ 青草里';
blue_25_route = '佳里 ─ 七股 ─ 土城子 ─ 科工區';

red_route = '安平工業區 ─ 仁德 ─ 關廟 ─ 龍崎';
red_1_route = '臺南公園 ─ 太子廟 ─ 關廟';
red_2_route = '臺南公園 ─ 仁德 ─ 上崙子 ─ 關廟';
red_3_route = '臺南公園 ─ 高鐵臺南站 ─ 關廟';
red_3_1_route = '保安轉運站 ─ 奇美博物館 ─ 臺南航空站<br /><div class="sub_title">奇美博物館假日公車</div>';
red_4_route = '臺南公園 ─ 中華醫大 ─ 奇美博物館';
red_10_route = '關廟 ─ 永康火車站 ─ 奇美醫院';
red_11_route = '關廟 ─ 龍崎 ─ 牛埔農塘';
red_12_route = '關廟 ─ 龍崎 ─ 烏山頭';
red_13_route = '關廟 ─ 阿蓮';
red_14_route = '關廟 ─ 高鐵臺南站 ─ 長榮大學';

brown_route = '新營 ─ 鹽水 ─ 學甲 ─ 佳里';
brown_1_route = '新營 ─ 鹽水 ─ 南鯤鯓 ─ 雙春、北門';
brown_2_route = '新營 ─ 鹽水 ─ 下中';
brown_3_route = '新營 ─ 鹽水 ─ 南港里';
brown_3_1_route = '新營 ─ 鐵線里';
brown_10_route = '學甲 ─ 麻豆';
brown_11_route = '學甲 ─ 頂洲';

orange_route = '佳里 ─ 麻豆 ─ 善化 ─ 玉井';
orange_1_route = '善化轉運站 ─ 大內 ─ 環湖 ─ 蒙正';
orange_2_route = '胡厝寮 ─ 善化 ─ 大內';
orange_3_route = '善化轉運站 ─ 安定 ─ 和順 ─ 臺南公園';
orange_4_route = '善化轉運站 ─ 南藝大 ─ 烏山頭水庫';
orange_4_1_route = '善化轉運站 ─ 官田工業區';
orange_5_route = '善化轉運站 ─ 官田 ─ 六甲';
orange_10_route = '大地莊園 ─ 麻豆 ─ 官田 ─ 南藝大';
orange_10_1_route = '麻豆 ─ 隆田火車站 ─ 官田工業區';
orange_11_route = '下營 ─ 麻豆 ─ 西港 ─ 臺南公園';
orange_12_route = '麻豆 ─ 善化 ─ 新市 ─ 臺南公園';
orange_20_route = '大內 ─ 環湖 ─ 玉井';

yellow_route = '白河 ─ 新營 ─ 柳營 ─ 麻豆';
yellow_1_route = '新營 ─ 柳營 ─ 六甲 ─ 南藝大';
yellow_2_route = '新營 ─ 柳營 ─ 六甲 ─ 王爺宮';
yellow_3_route = '新營 ─ 柳營 ─ 果毅後 ─ 德元埤';
yellow_4_route = '新營 ─ 二重溪 ─ 六甲';
yellow_5_route = '新營 ─ 紅毛厝 ─ 下營';
yellow_6_route = '新營 ─ 白沙屯 ─ 後壁火車站';
yellow_6_1_route = '新營 ─ 菁寮 ─ 土溝 ─ 白河<br /><div class="sub_title">假日農村樂活公車</div>';
yellow_7_route = '新營 ─ 東山 ─ 青山 ─ 仙公廟';
yellow_9_route = '新營 ─ 高鐵嘉義站 ─ 故宮南院';
yellow_10_route = '後壁 ─ 白河 ─ 六重溪';
yellow_10_1_route = '白河 ─ 六重溪 ─ 檳榔腳';
yellow_11_route = '白河 ─ 東山 ─ 青山';
yellow_11_1_route = '白河 ─ 東山 ─ 李子園';
yellow_11_2_route = '白河 ─ 東山 ─ 碧蓮寺';
yellow_12_route = '白河 ─ 關子嶺';
yellow_12_1_route = '白河 ─ 虎山里';
yellow_12_2_route = '關子嶺 ─ 水火同源 ─ 關子嶺<br /><div class="sub_title">關子嶺假日環狀公車</div>';
yellow_13_route = '白河 ─ 關子嶺 ─ 南寮';
yellow_14_route = '白河 ─ 三層崎';
yellow_14_1_route = '白河 ─ 甘宅 ─ 內角';
yellow_15_route = '白河 ─ 詔安厝';
yellow_16_route = '白河 ─ 東山 ─ 六甲 ─ 隆田火車站';
yellow_20_route = '麻豆 ─ 下營 ─ 林鳳營火車站';

urban_0_route = '臺南火車站 ─ 體育公園 ─ 臺南火車站';
urban_1_route = '臺南火車站 ─ 茄萣 ─ 興達遠洋漁港';
urban_2_route = '崑山科大 ─ 安平 ─ 四草、三鯤鯓';
urban_3_route = '海東國小 ─ 竹篙厝 ─ 復興國中';
urban_5_route = '桂田酒店 ─ 市立醫院、大甲里';
urban_6_route = '仁德轉運站 ─ 新興國宅 ─ 四鯤鯓';
urban_7_route = '臺南火車站 ─ 康寧大學';
urban_9_route = '臺南火車站 ─ 公親里、溪埔寮';
urban_10_route = '臺南火車站 ─ 科工區 ─ 鹿耳門天后宮';
urban_11_route = '大成路口 ─ 城西里';
urban_14_route = '臺南火車站 ─ 億載金城';
urban_15_route = '奇美醫院 ─ 大成國中';
urban_17_route = '安平原住民文化會館 ─ 興達港觀光魚市';
urban_18_route = '國民路 ─ 臺南站 ─ 塭南里 ─ 史博館';
urban_19_route = '安平原住民文化會館 ─ 大灣高中';
urban_20_route = '南紡購物中心 ─ 安南醫院 ─ 海東國小';
urban_21_route = '臺南火車站 ─ 鹽行 ─ 永康工業區';
urban_77_route = '安平原住民文化會館 ─ 南紡購物中心';
urban_77_1_route = '安平漁人碼頭 ─ 安平古堡 ─ 安平漁人碼頭<br /><div class="sub_title">安平環線假日公車</div>';
urban_77_2_route = '安平漁人碼頭 ─ 漁光島 ─ 興達港觀光魚市';
urban_239_route = '臺南火車站 ─ 太爺 ─ 茄萣';
urban_tainan_tourist_route = '臺南火車站 ─ 臺南火車站';

tourist_33_route = '新營 ─ 故宮南院 ─ 高鐵嘉義站 ─ 關子嶺　<div class="sub_title">關子嶺故宮南院線</div>';
tourist_88_route = '臺南公園 ─ 觀夕平台　<div class="sub_title">安平線</div>';
tourist_99_route = '臺南公園 ─ 四草 ─ 七股鹽山　<div class="sub_title">台江線</div>';

hsr_shuttle_H31_route = '安億橋 ─ 臺南市政府 ─ 高鐵臺南站　<div class="sub_title">高鐵快捷市府線</div>';
hsr_shuttle_H62_route = '桂田酒店 ─ 奇美醫院 ─ 高鐵臺南站　<div class="sub_title">高鐵快捷奇美線</div>';
hsr_shuttle_166_route = '鹽水 ─ 故宮南院 ─ 高鐵嘉義站';

highway_8035_route = '南化 ─ 內門 ─ 旗山轉運站';
highway_8041C_route = '鳳山 ─ 嘉南藥大 ─ 茄萣';
highway_8042_route = '臺南航空站 ─ 高鐵臺南站 ─ 實踐大學<br /><div class="sub_title">沙旗美月世界快線</div>';
highway_8046A_route = '臺南火車站 ─ 奇美博物館 ─ 高鐵左營站<br /><div class="sub_title">高南雙城快線</div>';
highway_8046_route = '臺南火車站 ─ 高雄火車站';
highway_8050_route = '臺南火車站 ─ 旗山轉運站 ─ 佛光山';
highway_7207_route = '嘉義 ─ 竹子腳 ─ 鹽水';
highway_7208_route = '嘉義 ─ 重寮 ─ 鹽水';
highway_7210_route = '嘉義 ─ 內角 ─ 白河';
highway_7214_route = '嘉義 ─ 內角 ─ 白河 ─ 關子嶺';
highway_7229_route = '嘉義 ─ 後壁 ─ 新營 ─ 柳營奇美醫院';
highway_7407_route = '新營 ─ 鹽水 ─ 朴子';
highway_7408_route = '新營 ─ 鹽水 ─ 南鯤鯓 ─ 好美里';
highway_7410_route = '新營 ─ 鹽水 ─ 布袋港';

STSP_green_route = '南科Park 17商場 ─ 高鐵臺南站　<div class="sub_title">南科巡迴巴士高鐵線</div>';
STSP_red_route = '臺鐵南科站 ─ 台達電 ─ Park 17商場　<div class="sub_title">南科巡迴巴士北環東線</div>';
STSP_orange_route = '臺鐵南科站 ─ 台積電 ─ Park 17商場　<div class="sub_title">南科巡迴巴士北環西線</div>';
STSP_blue_route = '臺鐵南科站 ─ 聯電 ─ Park 17商場　<div class="sub_title">南科巡迴巴士南環線</div>';
STSP_Shanhua_route = '臺鐵善化站 ─ 台積電 ─ Park 17商場　<div class="sub_title">南科巡迴巴士善化線</div>';

sightseeing_eastern_route = '臺南火車站 ─ 南紡購物中心 ─ 臺南火車站<br /><div class="sub_title">雙層巴士東環線</div>';
sightseeing_western_route = '臺南火車站 ─ 安平漁人碼頭 ─ 臺南火車站<br /><div class="sub_title">雙層巴士西環線</div>';